<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPm48rkk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPm48rkk/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPm48rkk.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPm48rkk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPm48rkk\appDevDebugProjectContainer([
    'container.build_hash' => 'Pm48rkk',
    'container.build_id' => 'e2c6639e',
    'container.build_time' => 1620806045,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPm48rkk');
